url_shortener/models.py
from datetime import datetime, timedelta
from .extensions import db
import string
from random import choices


class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_url = db.Column(db.String(4), unique=True)
    date_created = db.Column(db.DateTime, default=datetime.now)
    expiration_date = db.Column(db.DateTime, default=datetime.now() + timedelta(days=90))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_shortlink()

    def generate_shortlink(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=4))

        link = self.query.filter_by(short_url=short_url).first()

        if link:
            return self.generate_shortlink()

        return short_url

    def cleanup(self):
        return self.query.filter_by(date_created=datetime.now()).delete()

url_shortener/__init__.py
from flask import Flask
from .extensions import db
from .routes import short
from .models import Link

from apscheduler.schedulers.background import BackgroundScheduler


def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    app.register_blueprint(short)

    scheduler.init_app(app)
    scheduler.start()

    return app


# import from other_module...
# To avoid SQLAlchemy circular import, do the import at the bottom.
from .db_cleanup import scheduler

# link = Link()
# scheduler = BackgroundScheduler(daemon=True)
# scheduler.add_job(link.cleanup(), "interval", minutes=1)
# scheduler.start()

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .models import Link
from datetime import datetime, timedelta

from .extensions import db

short = Blueprint('short', __name__)


@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()
    if link.original_url[:4] not in ("http", "ftp:"):
        return redirect('https://'+link.original_url)
    return redirect(link.original_url)


@short.route('/')
def index():
    return render_template("index.html")


@short.route('/add_link', methods=['POST'])
def add_link():
    original_url = request.form['original_url']
    lifetime = int(request.form.get('lifetime'))
    expiry = datetime.now()+timedelta(days=lifetime)
    link = Link(original_url=original_url, expiration_date=expiry)

    db.session.add(link)
    db.session.commit()

    return render_template('link_added.html',
                           new_link=link.short_url, original_url=link.original_url)


@short.errorhandler(404)
def page_not_found(e):
    return '404', 404

###########
#          #
#   API's  ###
#          ####
##################


@short.route('/api/get_info/<short_url>')
def api_get_url_info(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()
    res = {"original url" : link.original_url, "creation date:" : link.date_created.strftime("%B %d, %Y"),
           "expiration date:" : link.expiration_date.strftime("%B %d, %Y")}
    return render_template('response.html', res=res)


@short.route('/api/s/<path:original_url>')
def api_shorten_url(original_url):
    link = Link(original_url=original_url)

    db.session.add(link)
    db.session.commit()

    return link.short_url

url_shortener/templates/all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All entries</title>
</head>
<body>
<table>
    <tbody>    {% for link in links %}
    <tr>
        <td>{{ link.original_url }}</td>
        <td>{{ url_for('short.redirect_to_url', short_url=link.short_url, _external=True) }}</td>
        <td>{{ link.date_created }}</td>
        <td>{{ link.expiration_date }}</td>
    </tr>
{% endfor %}</tbody>

</table>

</body>
</html>

url_shortener/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shorty</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
<div class="valign-wrapper" style="width:100%;height:100%;position: absolute;">
    <div class="valign" style="width:100%;">
        <div class="container">
           <div class="row">
              <div class="col s12 m6 offset-m3">
                 <div class="card">
                    <div class="card-content">
                       <span class="card-title black-text">Введіть посилання</span>
                          <form method="post" action="{{url_for('short.add_link') }}">
                            <input type="text" name="original_url">
                              <div class="row">
                                  <div class="col s12"><label>Срок збереження</label>
                                    <select name="lifetime" class="browser-default">
                                    <option value="1">День</option>
                                    <option value="7">Тиждень</option>
                                    <option value="31">Місяць</option>
                                    <option value="90" selected>Три місяці</option>
                                    <option value="180">Півроку</option>
                                    <option value="365">Рік</option>
                                    </select>
                                  </div>
                             </div>

                        <button type="submit" class="btn">Скоротити</button>

                     </form>
                 </div>
              </div>
           </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
<div class="valign-wrapper" style="width:100%;height:100%;position: absolute;">
    <div class="valign" style="width:100%;">
        <div class="container">
            <div class="row">
                <div class="col s12 m6 offset-m3">
                    <div class="card">
                        <div class="card-content" style="background: linear-gradient(110deg, #169873  60%, #9EBD6E 60%);">
                            <div class="row">
                                  <div class="col s12">
                                      <h5 class="center-align">Ваше нове посилання  : <br/>
                                          <div style="background-color:white; margin-top:1em;">{{ url_for('short.redirect_to_url', short_url=new_link, _external=True)}}</div> </h5> <br/>
                                    Старий лінк: {{ original_url }}
                                  </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



</body>
</html>

url_shortener/templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ res }}
</body>
</html>